# config/services.yaml

parameters:
    mail_user: '%env(STRATIX_MAIL_USER)%'
    mail_pass: '%env(STRATIX_MAIL_PASS)%'
    catalogues_directory: '%kernel.project_dir%/public/uploads/catalogues'
    # On garde l'ancienne pour ne pas casser d'autres services si besoin, 
    # mais on ajoute la clé Grok
    grok_api_key: '%env(GROK_API_KEY)%'

services:
    # configuration par défaut
    _defaults:
        autowire: true      
        autoconfigure: true 

    # enregistre toutes les classes du src/ comme services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # --- MODIFICATION ICI ---
    # On remplace GeminiService par GrokService
    App\Service\GrokService:
        arguments:
            $apiKey: '%grok_api_key%'