# config/services.yaml

parameters:
    mail_user: '%env(STRATIX_MAIL_USER)%'
    mail_pass: '%env(STRATIX_MAIL_PASS)%'
    catalogues_directory: '%kernel.project_dir%/public/uploads/catalogues'
    # On garde l'ancienne pour ne pas casser d'autres services si besoin, 
    # mais on ajoute la clé Grok
    grok_api_key: '%env(GROK_API_KEY)%'
      
services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\PictureService:
        arguments:
            $uploadDir: '%kernel.project_dir%/public/uploads/events'


    App\Service\MeetingSummaryService:  
        arguments:
            $apiKey: '%env(FEED_GEMINI_API_KEY)%'

    App\Service\RecommendationService:
        arguments:
            $apiKey: '%env(REC_GROQ_API_KEY)%'

    App\Service\GroqService:
        arguments:
            $apiKey: '%grok_api_key%'
            
    App\Service\AiResumeService:
        arguments:
            $apiKey: '%env(OPENAI_API_KEY_PROJET)%'

    App\Service\RecaptchaService:
        arguments:
            $recaptchaSecretKey: '%env(RECAPTCHA_SECRET_KEY)%'

    App\Controller\ResetPasswordController:
        arguments:
            $defaultTransport: '@mailer.default_transport'
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Service\ParticipationService:
        arguments:
            $eventMailer: '@mailer.transports'

    App\Command\NotifyDeadlinesCommand:
        arguments:
            $projetMailer: '@mailer.transports'

    
